### ISSUE TITLE
Not really an issue

### ISSUE THREAD

**Issue by ijunaid8989** [cbh6/vuejs-socketio-chat#1]
Nice code. I didn't find anything to interact with you. I wanted to know you learned it through some tutorial? the code you wrote and everything stuff? I found many videos but not with Bulma and the way you typed it, Can you please tell me that.???

**Comment by cbh6** [comment]
Hi @ijunaid8989, I don't know what do you really mean.

Maybe this would be useful:
- Chat components were all written in the same js file with socket.io client logic.
You can find more info about vuejs components here: https://vuejs.org/v2/guide/components.html
- Bulma is just for styling, more info about it can be found here https://bulma.io/
- I also got inspired by this repo https://github.com/ibbatta/vuejs-socketio.

I wrote a post on medium explaining a little bit how chat was coded https://medium.com/@cri.bh6/building-a-real-time-chat-with-vuejs-nodejs-and-socketio-18f66e8da5d7

You can also find useful these posts:
https://medium.com/@msanathkumar/building-a-simple-real-time-chat-application-using-socket-io-express-and-vue-js-d263c08a4c59 (This one is really good)
https://medium.com/@michaelmangial1/getting-started-with-vue-js-socket-io-8d385ffb9782

First one is really good
*
