### ISSUE TITLE
Auto-scroll when new message is posted

### ISSUE THREAD

**Issue by stiofanoriain** [cbh6/vuejs-socketio-chat#2]
Hi there

Love this project. I'm not sure if you work on it anymore, but I noticed a bug (?) which is affecting the current functionality.

When someone posts a new message, it is not visible on screen unless you manually scroll down.

I think it would be better if the page auto-scrolled whenever a new messaged is posted.

For example, let's say these are the messages on screen:

![image](https://user-images.githubusercontent.com/24823587/46250240-1d7ad700-c469-11e8-8c16-58eb1dfe9ae8.png)

When a new message is posted, the messages on screen do not change. The user has to manually scroll down the page to see them.

Cheers

**Comment by cbh6** [comment]
Hi, thanks for noticing about this issue. 
I have fixed it right now. There was an error in the code that made auto scroll fail when new message arrived. 

😄 cheers
